<?php

return [
  'Status',
  'Title',
  'Product Type',
  'Seller SKU',
  'Brand',
  'Update Delete',
  'Product ID',
  'Product ID Type',
  'Product Name',
  'Item Type Keyword',
  'Manufacturer',
  'Manufacturer Part Number',
  'Product Description',
  'Model Year',
  'Model Name',
  'Model Number',
  'Product Exemption Reason',
  'Outer Material',
  'Outer Material',
  'Outer Material',
  'Outer Material',
  'Outer Material',
  'Care Instructions',
  'Care Instructions',
  'Closure Type',
  'Fuel Type',
  'Lining Material',
  'Edition',
  'Audio Encoding Language',
  'Audio Encoding Language',
  'Audio Encoding Language',
  'Audio Encoding Language',
  'Audio Encoding Language',
  'Grade Rating',
  'Maximum Aperture',
  'Video Capture Resolution',
  'Video Capture Resolution',
  'Max Aperture Unit',
  'Main Image URL',
  'Other Image URL1',
  'Other Image URL2',
  'Other Image URL3',
  'Other Image URL4',
  'Other Image URL5',
  'Other Image URL6',
  'Other Image URL7',
  'Other Image URL8',
  'Swatch Image URL',
  'Parentage',
  'Parent SKU',
  'Relationship Type',
  'Variation Theme',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Key Product Features',
  'Generic Keyword',
  'Color',
  'Color Map',
  'Material Type',
  'Material Type',
  'Material Type',
  'Material Type',
  'Material Type',
  'Additional Features',
  'Additional Features',
  'Additional Features',
  'Additional Features',
  'Additional Features',
  'Musical Style',
  'Instrument Key',
  'Range',
  'Polar Pattern',
  'Maximum Sample Rate Unit Of Measure',
  'Maximum Sample Rate',
  'signal-format',
  'Connector Type',
  'Connector Type',
  'Connector Type',
  'Connector Type',
  'Connector Type',
  'Back Material Type',
  'Fretboard Material Type',
  'Neck Material Type',
  'Top Material Type',
  'Body Material Type',
  'Number of Keys',
  'Key Action',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Hardware Connectivity',
  'Operating System',
  'supported-software',
  'Number of Channels',
  'Output Wattage',
  'Number of Strings',
  'Hand Orientation',
  'Skill Level',
  'Size',
  'Amperage Unit Of Measure',
  'Item Type Name',
  'Range Unit Of Measure',
  'Wattage Unit Of Measure',
  'Output Wattage Unit',
  'Impedance',
  'Tolerance Held',
  'Audio Sensitivity',
  'Season and collection year',
  'Wattage',
  'Amperage',
  'Voltage',
  'Compatible Devices',
  'Compatible Devices',
  'Compatible Devices',
  'Compatible Devices',
  'Compatible Devices',
  'Number of Boxes',
  'Audio Sensitivity Unit Of Measure',
  'Connectivity Technology',
  'Included components',
  'Included components',
  'Included components',
  'Included components',
  'Included components',
  'Impedance Unit Of Measure',
  'Voltage Unit Of Measure',
  'String Material Type',
  'String Gauge',
  'Speaker Count',
  'Guitar Pick Thickness',
  'Style',
  'Team Name',
  'League Name',
  'Number of Pieces',
  'Certification',
  'Certification',
  'Certification',
  'Certification',
  'Certification',
  'Shade Material',
  'Number Of Bulb Sockets',
  'Number Of Blades',
  'Power Source',
  'Maximum Supported Wattage',
  'Light Source Type',
  'Brightness Unit Of Measure',
  'Color Temperature',
  'Colour Temperature Unit Of Measure',
  'Mounting Type',
  'Luminous Flux',
  'Scent',
  'Average Life Span',
  'Light Path Distance Unit Of Measure',
  'Runtime Unit Of Measure',
  'Light Source Wattage Unit of Measure',
  'Light Path Distance',
  'Is Assembly Required',
  'Battery Description',
  'Water Resistance Level',
  'Average Life Span Unit of Measure',
  'Run Time',
  'Max Compatible Light Source Wattage Unit',
  'Antenna Location',
  'Horsepower Unit Of Measure',
  'Controller Type',
  'Installation Method',
  'Audible Noise',
  'Noise Level Unit Of Measure',
  'Speed Unit Of Measure',
  'Insulation Resistance Unit Of Measure',
  'Maximum Range Unit',
  'Maximum Range',
  'Frame Material Type',
  'Seating Capacity',
  'Number of doors',
  'Bed Frame Type',
  'Assembly Instructions',
  'Seat Depth',
  'Room Type',
  'Room Type',
  'Room Type',
  'Room Type',
  'Room Type',
  'Drawers',
  'Number of Shelves',
  'Back Style',
  'Seat Depth Unit',
  'Rechargeable Battery Included',
  'Wireless Technology',
  'Total Number of HDMI Ports',
  'Total USB Ports',
  'Hardware Platform',
  'Hardware Platform',
  'Hardware Platform',
  'Includes Remote',
  'Frequency Response Unit Of Measure',
  'Total USB 3.0 Ports',
  'Signal-to-Noise Ratio Unit',
  'Frequency Response',
  'Total USB 2.0 Ports',
  'Plug Format',
  'Catalog Number',
  'Is Memorabilia',
  'Is Autographed',
  'Intended Use',
  'Intended Use',
  'Intended Use',
  'Intended Use',
  'Intended Use',
  'Target Audience',
  'Target Audience',
  'Target Audience',
  'Target Audience',
  'Target Audience',
  'Other Attributes',
  'Other Attributes',
  'Other Attributes',
  'Other Attributes',
  'Other Attributes',
  'Subject Matter',
  'Subject Matter',
  'Subject Matter',
  'Subject Matter',
  'Subject Matter',
  'Item Styling',
  'AC Adapter Included',
  'Pickguard Description',
  'Digital Audio Protocol',
  'Mixer Channel Quantity',
  'Wireless Microphone Frequency Unit Of Measure',
  'Wireless Microphone Frequency',
  'Speaker Amplification Type',
  'Drum Set Piece Quantity',
  'Guitar Bridge System',
  'Guitar Pickup Configuration',
  'Mallet Hardness',
  'Platinum Keywords',
  'Platinum Keywords',
  'Platinum Keywords',
  'Platinum Keywords',
  'Platinum Keywords',
  'Thread Type',
  'Stem Length Unit',
  'Battery Average Life Unit Of Measure',
  'Lithium Battery Voltage Unit of Measure',
  'Display Type',
  'Case Material Type',
  'Case Material Type',
  'Calibration Description',
  'Battery Average Life',
  'Measurement Accuracy',
  'Lens Material',
  'Resolution',
  'Lithium Battery Voltage',
  'Fill Material Type',
  'Liquid Packaging Type',
  'display_resolution_maximum_unit_of_measure',
  'Maximum Horsepower Unit',
  'magnification_minimum_unit_of_measure',
  'Luminous Intensity Unit Of Measure',
  'Golf Club Loft Unit Of Measure',
  'Seating group',
  'Option type',
  'diving_clothing_thickness_unit_of_measure',
  'Target audience',
  'resistance_unit_of_measure',
  'Maximum Energy Output Unit Of Measure',
  'Design',
  'Event Name',
  'Included Features',
  'Package Contents',
  'Seasons',
  'Country/Region as Labeled',
  'Fur Description',
  'Sport Type',
  'Sport Type',
  'Minimum Tension Rating',
  'Minimum Tension Rating Unit Of Measure',
  'Maximum Tension Rating',
  'Maximum Tension Rating Unit Of Measure',
  'Speed Rating',
  'Number of Programs',
  'Maximum Resistance',
  'Maximum Resistance Unit Of Measure',
  'Floor Area',
  'Floor Area Unit Of Measure',
  'Belt Style',
  'Collar Type',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Department',
  'Front Pleat Type',
  'Glove Type',
  'Neck Style',
  'Pattern Style',
  'Pocket Description',
  'Sock Height',
  'Theme',
  'Top Style',
  'UV Protection',
  'Wheel Type',
  'Loft',
  'Grip Type',
  'Engine Displacement',
  'Engine Displacement Unit Of Measure',
  'Software Included',
  'Bike Type',
  'Brake Style',
  'Suspension Type',
  'Speed',
  'Lock Type',
  'Diving Clothing Thickness',
  'Handle Material',
  'Breaking Point',
  'Maximum Tension Load Unit Of Measure',
  'HP',
  'Handle Type',
  'Subject',
  'Water Resistance Depth',
  'Water Resistance Depth Unit Of Measure',
  'Hole Count',
  'Caliber',
  'Flavor',
  'Lens Color',
  'Fuel Capacity',
  'Fuel Capacity Unit Of Measure',
  'Blade Type',
  'Turn Radius',
  'Turn Radius Unit Of Measure',
  'Loudness',
  'Number of Pages',
  'GeographicCoverage',
  'GeographicCoverage',
  'GeographicCoverage',
  'GeographicCoverage',
  'GeographicCoverage',
  'Static Load Capacity',
  'Static Load Capacity Unit Of Measure',
  'Heat Output',
  'Heat Output Unit Of Measure',
  'Temperature Rating',
  'Temperature Rating Degrees Unit Of Measure',
  'Lens Type',
  'BTUs',
  'R-Value',
  'Insulation Material Type',
  'Pad Type',
  'Number Of Poles',
  'Folded Size',
  'Burn Time',
  'Light Source Operating Life Unit Of Measure',
  'Light Intensity',
  'Magnification Minimum',
  'Shaft Material',
  'Shaft Style Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Fit Type',
  'Maximum Pitch Speed',
  'Maximum Pitch Speed Unit Of Measure',
  'Athlete',
  'Operation Mode',
  'Monitor Native Resolution',
  'Memory Storage Capacity',
  'Memory Storage Capacity Unit Of Measure',
  'Display Resolution Maximum',
  'Number of Horses',
  'sound_pressure_unit_of_measure',
  'CounterDepth',
  'Compatible Counter Depth Unit Of Measure',
  'Speaker Type',
  'Compatibility Options',
  'Shelf Type',
  'breed_recommendation',
  'directions',
  'Number of Sets',
  'Occasion',
  'Ink Colour',
  'Cover Material Type',
  'Number of Labels',
  'Recorder Track Count',
  'Maximum Pressure',
  'Maximum Operating Pressure Unit Of Measure',
  'Head Style',
  'Grit Number',
  'Grit Type',
  'Grit Material Type',
  'Maximum Rotational Speed',
  'Maximum Rotational Speed Unit Of Measure',
  'Manufacturer Warranty Description Labor',
  'Item Torque',
  'Item Torque Unit Of Measure',
  'Upper Temperature Rating',
  'Upper Temperature Rating Unit Of Measure',
  'Data Transfer Rate',
  'Maximum Power Unit Of Measure',
  'Output Power',
  'Maximum Load Current',
  'Power Consumption Size Unit of Measure',
  'Cable Type',
  'Cable Type',
  'Cable Type',
  'Cable Type',
  'Air Flow Efficiency',
  'Current Rating',
  'Nominal Voltage',
  'Maximum Power',
  'Trigger Voltage Unit Of Measure',
  'Air Flow Efficiency Unit',
  'Maximum Switching Voltage Unit',
  'Frequency Unit',
  'Maximum Voltage Unit',
  'Output Power Unit',
  'Operating Temperature Unit',
  'Trigger Voltage',
  'Maximum Operating Distance',
  'Power level unit of measure',
  'Maximum Storage Temperature',
  'Temperature Range Unit Of Measure',
  'Data Transfer Rate Unit Of Measure',
  'Current Rating Unit',
  'Power level',
  'Nominal Voltage Unit Of Measure',
  'Maximum Switching Voltage',
  'Temperature Range',
  'Frequency',
  'Operating Temperature',
  'AC Adapter Current',
  'Operating Voltage Unit',
  'Supply Voltage Unit',
  'Maximum Voltage',
  'Resistance',
  'Maximum Load Current Unit',
  'Operating Voltage',
  'Maximum Operating Distance Unit Of Measure',
  'Power Consumption Size',
  'Gauge Decimal Value',
  'Supply Voltage',
  'Maximum Current Unit Of Measure',
  'Maximum Storage Temperature Unit',
  'Horsepower',
  'Handle Lever Placement',
  'Number of Teeth',
  'OEM Part Number',
  'OEM Part Number',
  'OEM Part Number',
  'OEM Part Number',
  'OEM Part Number',
  'Shank Type',
  'Effective Still Resolution',
  'Compatible Phone Models',
  'Compatible Phone Models',
  'Compatible Phone Models',
  'GPS Geotagging Functionality',
  'Camera Description',
  'Camera Description',
  'Has Color Screen',
  'Human-Interface Input',
  'Human-Interface Input',
  'Human-Interface Input',
  'Human-Interface Input',
  'Human-Interface Input',
  'Optical Sensor Resolution',
  'Front Photo Sensor Resolution Unit Of Measure',
  'Supported Application',
  'Front Photo Sensor Resolution',
  'Effective Still Resolution Unit Of Measure',
  'Lifestyle',
  'Lifestyle',
  'Lifestyle',
  'Lifestyle',
  'Lifestyle',
  'Optical Sensor Resolution Unit',
  'Lower Temperature Rating',
  'Lower Temperature Rating Unit Of Measure',
  'Minimum Storage Temperature',
  'Minimum Storage Temperature Unit',
  'Exterior Finish',
  'Thread Style',
  'Control Type',
  'MicrophoneTechnology',
  'Headphone Jack',
  'Noise Control',
  'Customer Service Phone Number',
  'Number of Ports',
  'Internet Applications',
  'lens_addition_power_unit_of_measure',
  'Power Plug Type',
  'Digital Storage Capacity',
  'Digital Storage Capacity Unit Of Measure',
  'Fastening Type',
  'Is the item dishwasher safe?',
  'Material Type FREE',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Vehicle Type Compatibility',
  'Viscosity Unit',
  'Supported Media Type',
  'Supported Media Type',
  'Supported Media Type',
  'Supported Media Type',
  'Supported Media Type',
  'Compatible Mountings',
  'Compatible Mountings',
  'Digital Zoom',
  'Optical Zoom',
  'Minimum Shutter Speed',
  'Maximum Shutter Speed',
  'Continuous Shooting Speed',
  'Camera Flash Type',
  'lens',
  'Image Stabilization Type',
  'Viewfinder Type',
  'Viewfinder Type',
  'Viewfinder Type',
  'Real Angle Of View',
  'Focus Type',
  'Audio Output Type',
  'Photo Sensor Technology',
  'Iso Range',
  'Macro Focus Range',
  'Self Timer Duration',
  'Zoom',
  'Continuous Shooting Speed Unit',
  'Photo Sensor Resolution',
  'Max Shutter Speed Unit',
  'Optical Zoom Unit',
  'Self Timer Duration Unit',
  'Has Self-Timer',
  'Minimum Shutter Speed Unit',
  'Macro Focus Range Unit',
  'Video Capture Format',
  'Real Angle of View Unit',
  'Photo Sensor Resolution Unit Of Measure',
  'Digital Zoom Unit',
  'Speaker Connectivity',
  'Maximum Wattage',
  'Speaker Maximum Input Power Unit Of Measure',
  'Subwoofer Wattage',
  'Speaker Maximum Output Power Unit',
  'Speaker Maximum Output Power',
  'Speaker Nominal Output Power Unit',
  'Subwoofer Amplifier Wattage Unit',
  'Speaker Nominal Output Power',
  'Certifying Authority Name',
  'Frequency Response Curve',
  'Surface Treatment Method',
  'Instrument',
  'Instrument',
  'Instrument',
  'Instrument',
  'Instrument',
  'Geographic Jurisdiction',
  'Item Depth Unit Of Measure',
  'flash_point_unit_of_measure',
  'Finish Types',
  'Finish Types',
  'scale_length_unit_of_measure',
  'Grip Material Type',
  'LightingMethod',
  'Base Type',
  'Color Rendering Index',
  'Light Source Special Features',
  'Annual Energy cost',
  'Control Method',
  'Energy Guide Cost Disclosure',
  'Bulb Shape Size',
  'Connectivity Protocol',
  'Connectivity Protocol',
  'Connectivity Protocol',
  'Connectivity Protocol',
  'Connectivity Protocol',
  'Bulb Base',
  'Shade Color',
  'Item Pitch Unit Of Measure',
  'Coverage',
  'Sensor Technology',
  'Construction Type',
  'Furniture Finish',
  'Arm Style',
  'Seat Material Type',
  'Door Style',
  'Remote Control Type',
  'Microphone Form Factor',
  'Frequency Range',
  'Cable Length Decimal Value',
  'Signal-to-Noise Ratio',
  'Output Channel Quantity',
  'Output Voltage Unit',
  'Input Voltage Unit',
  'Output Voltage',
  'Input Voltage',
  'Outside Diameter Unit Of Measure',
  'Inside Height Unit',
  'Inside Length Unit',
  'Output Type',
  'Output Type',
  'Output Type',
  'Output Type',
  'Output Type',
  'Stem Outside Diameter String Value',
  'Bezel Material Type',
  'Manufacturer Series Number',
  'Inside Diameter Unit Of Measure',
  'Inside Width Unit',
  'Readout Accuracy',
  'Drive System',
  'Stem Outside Diameter Unit Of Measure',
  'Thread Pitch Unit Of Measure',
  'Shaft Material',
  'Shipping options',
  'Watch Movement Type',
  'Number Of Resistance Levels',
  'Target Zones',
  'Number Of Carriage Positions',
  'Number Of Exercises',
  'Number Of Foot Positions',
  'Number Of Head Positions',
  'Number Of Springs',
  'Maximum Incline Percentage',
  'Control Program Name',
  'Resistance Mechanism',
  'Scale',
  'Alarm',
  'Bottom Style',
  'Cuff Type',
  'Fabric Wash',
  'Leg Style',
  'Sleeve Type',
  'Strap Type',
  'Support Type',
  'Underwire Type',
  'Flex',
  'Thread Pitch',
  'Line Weight',
  'Tension Supported',
  'Fishing Line Type',
  'Backing Line Capacity',
  'Bearing Material Type',
  'Sonar Type',
  'Hull Shape',
  'Deck Dimensions Unit Of Measure',
  'Number Of Speeds',
  'Action',
  'Frequency Band',
  'Life Vest Type',
  'Cycles',
  'Rotation',
  'Orientation',
  'Number Of Power Levels',
  'Position Accuracy',
  'Navigation Routes',
  'Waypoints',
  'Item Impact Force',
  'Rounds',
  'Blade Shape',
  'Calf Size',
  'Fitting Type',
  'Number Of Pockets',
  'Static Elongation Percentage',
  'UIAA Fall Rating',
  'Number Of Gear Loops',
  'Access Location',
  'Boil Rate Description',
  'Water Bottle Cap Type',
  'State',
  'Lamp',
  'Minimum Torso Measurement',
  'Occupancy',
  'Magnification Maximum',
  'Curvature',
  'Fencing Pommel Type',
  'Head Size',
  'Uniform Number',
  'Guard Material Type',
  'Usage Capacity Unit Of Measure',
  'Display Color Support',
  'Fulfillment Center Shelf Life Unit',
  'Vendor Return Serial Number Required',
  'Blade Material Type',
  'Energy Guide Capacity',
  'Number of cds',
  'Minimum Age Recommendation',
  'Fixed or adjustable height',
  'Material Composition',
  'Base',
  'Number of dvds',
  'Mount height string unit of measure',
  'Maximum Age Recommendation',
  'Thread Count',
  'Audio Input',
  'Connector Gender',
  'Connector Gender',
  'Connector Gender',
  'Connector Gender',
  'Connector Gender',
  'Amplifier Type',
  'Bands',
  'Paper Finish',
  'Number of Hooks',
  'Year Range',
  'number of lines',
  'DrawerType',
  'Head Length Unit',
  'Head Type',
  'Head Angle Unit',
  'Head Height Decimal Value',
  'Head Height Unit Of Measure',
  'Head Diameter Unit',
  'Head Diameter Decimal Value',
  'Head Length Decimal Value',
  'Head Angle',
  'Number of tiers',
  'Bulb Diameter',
  'Leakage Current',
  'Enclosure',
  'Minimum Current',
  'Minimum Coil Voltage Unit',
  'Maximum Frequency',
  'Minimum Input Voltage Unit',
  'Number of Receivers',
  'Input Capacitance',
  'Sensing Distance',
  'Maximum Trimmer Voltage',
  'Insert Diameter Unit',
  'Input Current',
  'Minimum Release Voltage Unit',
  'Minimum Capacitance Unit',
  'Number of Outputs',
  'Bulb Diameter Unit Of Measure',
  'Number of Circuits',
  'Output Current Unit',
  'Sensing Mode',
  'Minimum Capacitance',
  'Operating Wavelength Unit',
  'Shielding Type',
  'Input Current Unit',
  'Leakage Current Unit',
  'Minimum Voltage',
  'Minimum Operating Distance',
  'Number of Rows',
  'Inductance',
  'Maximum Switching Current',
  'Minimum Control Voltage',
  'Minimum Control Voltage Unit',
  'Inductance Unit',
  'Minimum Voltage Unit',
  'Jacket Material',
  'Maximum Control Voltage',
  'Maximum Coil Voltage',
  'Minimum Coil Voltage',
  'Number of Shafts',
  'Number of Wires',
  'Contact Plating Material',
  'Number of Conductors',
  'Pin Type',
  'Minimum Frequency',
  'Electrode',
  'Current',
  'Maximum Control Voltage Unit',
  'Output Current',
  'Maximum Capacitance',
  'Minimum Switching Voltage',
  'Maximum Trimmer Voltage Unit',
  'Ferrule Material',
  'Maximum Operating Voltage',
  'Number of Sections',
  'Sensing Distance Unit',
  'Maximum Frequency Unit',
  'Beam Size String Value',
  'Input Capacitance Unit',
  'Operating Wavelength',
  'Minimum Operating Distance Unit',
  'Terminal',
  'Load Capacitance Unit',
  'Minimum Frequency Unit',
  'Number of Terminals',
  'Minimum Input Impedance Unit',
  'Minimum Switching Voltage Unit',
  'Minimum Release Voltage',
  'Contact Material',
  'Maximum Capacitance Unit',
  'Maximum Operating Voltage Unit',
  'Number Of Contacts',
  'Sensing Method',
  'Maximum Coil Voltage Unit',
  'Number of Pins',
  'Minimum Input Voltage',
  'Minimum Current Unit',
  'Insert Diameter String Value',
  'Load Capacitance',
  'Switch Style',
  'Jacket Color',
  'Number of Macrocells',
  'Sleeve Material',
  'Maximum Switching Current Unit',
  'Package Type',
  'Contact Type',
  'Minimum Input Impedance',
  'Number of Cells',
  'Is the item OEM authorized?',
  'Service Provider',
  'Sub Brand',
  'Alarm Clock',
  'Cellular Technology',
  'Maximum Input Voltage Unit',
  'Capacitance',
  'Required Voltage Unit',
  'Coil Resistance',
  'Housing Diameter Unit',
  'Contact Input Power',
  'Contact Input Power Unit',
  'Maximum Output Voltage Unit',
  'Minimum Operating Voltage Unit',
  'Coil Power Unit',
  'Contact Current',
  'Capacitance Unit',
  'Maximum Output Voltage',
  'Minimum Load Current Unit',
  'Housing Diameter String Value',
  'Minimum Output Voltage Unit',
  'Required Voltage',
  'Coil Resistance Unit',
  'Supply Current',
  'Forward Current',
  'Minimum Output Voltage',
  'Beam Size Unit',
  'Maximum Supply Voltage Unit',
  'Contact Initial Resistance unit',
  'Supply Power',
  'Maximum Input Voltage',
  'Minimum Supply Voltage Unit',
  'Supply Power Unit',
  'Coil Voltage Unit',
  'Minimum Load Current',
  'Input Temperature Unit',
  'Minimum Operating Voltage',
  'Minimum Resistance',
  'Contact Capacity Unit',
  'Output Capacitance Unit',
  'Input Temperature',
  'Minimum Resistance Unit',
  'Contact Initial Resistance',
  'Nominal Power Unit',
  'Contact Current Unit',
  'Maximum Supply Voltage',
  'Nominal Power',
  'Nominal Current',
  'Minimum Supply Voltage',
  'capacitance_tolerance',
  'Supply Current Unit',
  'Coil Power',
  'Housing length String Value',
  'Coil Voltage',
  'Output Capacitance',
  'Contact Capacity',
  'Nominal Current Unit',
  'Forward Current Unit',
  'Housing length Unit',
  'Head Diameter',
  'Screw Point Style',
  'Shoulder Diameter',
  'Shoulder Diameter Unit Of Measure',
  'Shoulder Length',
  'Shoulder Length Unit Of Measure',
  'Thread Coverage',
  'Thread Length',
  'Thread Length Unit Of Measure',
  'Thread Size',
  'Fastener Size',
  'compatible_with_pipe_size_unit_of_measure',
  'Fastener Type',
  'Headphone Folding Features',
  'Cable Features',
  'Compatibility',
  'Compatibility',
  'Compatibility',
  'Compatibility',
  'Compatibility',
  'Series ID',
  'Audio Output Mode',
  'Number of Audio Channels',
  'Is the liquid product double sealed?',
  'Output Connector Type',
  'Platform for Display',
  'Partslink Number',
  'Partslink Number',
  'Partslink Number',
  'Partslink Number',
  'Auto Part Position',
  'Product Compliance Certificate',
  'Configuration',
  'Flash Modes Description',
  'Flash Modes Description',
  'Exposure Control Type',
  'Exposure Control Type',
  'Exposure Control Type',
  'Exposure Control Type',
  'Flash Type',
  'Image Sensor Type',
  'Aperture modes',
  'For Use With',
  'Flash Sync Speed',
  'Audio Recording',
  'Light Sensitivity',
  'Autofocus',
  'Shooting Modes',
  'HDMI Type',
  'Sensor Cleaning Method',
  'Optical Sensor Size',
  'Sensor Type',
  'File Format',
  'Number of Zones',
  'Total Harmonic Distortion Rated Power',
  'Sensitivity Unit',
  'Sensitivity',
  'Input-Device Interface',
  'Size Map',
  'Item Length Unit Of Measure',
  'Item Length',
  'Item Height',
  'Item Width',
  'Website Shipping Weight Unit Of Measure',
  'Shipping Weight',
  'Scale Length',
  'Item Width Unit Of Measure',
  'Item Depth',
  'Unit Count',
  'Item Height Unit Of Measure',
  'Unit Count Type',
  'Speaker Size Unit Of Measure',
  'Speaker Size',
  'Item Diameter Unit Of Measure',
  'Item Diameter',
  'Item Shape',
  'Bulb Length',
  'Bulb Length Unit Of Measure',
  'Item Display Depth Unit Of Measure',
  'Item Display Diameter Unit Of Measure',
  'Annual Energy Consumption',
  'Annual Energy Consumption Unit of Measure',
  'Bulb Diameter',
  'Light Source Diameter Unit of Measure',
  'Maximum Weight Recommendation Unit Of Measure',
  'Manufacturer Recommended Maximum Weight',
  'Item Depth Front To Back',
  'Item Depth Unit',
  'Item Width Side to Side',
  'Item Width Unit',
  'Item Height Base to Top',
  'Item Height Unit',
  'Item Display Length Unit Of Measure',
  'Item Display Width Unit Of Measure',
  'Item Display Height Unit Of Measure',
  'Height Top to Bottom',
  'Capacity Unit Of Measure',
  'Item Width Shorter Edge',
  'Item Width Unit',
  'Item Length Unit',
  'Item Height Unit',
  'Item Length Longer Edge',
  'Capacity',
  'Item Display Diameter',
  'Seat Height',
  'Seat Height Unit Of Measure',
  'Knitting Needle Type',
  'Seat Width',
  'Item Firmness Description',
  'Seat Width Unit Of Measure',
  'Cable Length Unit Of Measure',
  'Outside Diameter',
  'Cable Length',
  'Thickness',
  'Item Thickness Unit Of Measure',
  'System of Measurement',
  'Blade Length',
  'Maximum Weight Capacity',
  'Maximum Weight Capacity Unit Of Measure',
  'Liquid Volume',
  'Liquid Volume Unit',
  'Blade Length Unit Of Measure',
  'Head Size',
  'Inseam Length Unit Of Measure',
  'Deck Width Unit',
  'Shoe Width Unit',
  'maximum_compatible_boot_size_unit_of_measure',
  'Volume Capacity Name Unit Of Measure',
  'minimum_compatible_boot_size_unit_of_measure',
  'Floor Length',
  'Floor Length Unit Of Measure',
  'Floor Width',
  'Floor Width Unit Of Measure',
  'Maximum Stride Length',
  'Maximum Stride Length Unit Of Measure',
  'Cup Size',
  'Shoe Width',
  'Sleeve Length',
  'Sleeve Length Unit Of Measure',
  'Width',
  'Waist Size',
  'Waist Size Unit Of Measure',
  'Grip Size',
  'Rim Size',
  'Rim Size Unit Of Measure',
  'Crank Length',
  'Crank Length Unit Of Measure',
  'Top Tube Length',
  'Top Tube Length Unit Of Measure',
  'Wheel Size',
  'Wheel Size Unit Of Measure',
  'Brake Width',
  'Brake Width Unit Of Measure',
  'Inseam Length',
  'Frame Height',
  'Frame Size Unit Of Measure',
  'Volume',
  'Lure Weight',
  'Lure Weight Unit Of Measure',
  'Beam Width',
  'Beam Width Unit Of Measure',
  'Centerline Length',
  'Centreline Length Unit Of Measure',
  'Compatible Hose Diameter',
  'Compatible Hose Diameter Unit Of Measure',
  'Boom Length',
  'Boom Length Unit Of Measure',
  'Deck Length',
  'Deck Width',
  'Item Display Length',
  'DeckDimensionUnitOfMeasure',
  'Item Display Weight',
  'Item Display Weight Unit Of Measure',
  'Boot Size',
  'Maximum Compatible Boot Size',
  'Minimum Compatible Boot Size',
  'Apparent Scale Size',
  'Apparent Scale Size Unit Of Measure',
  'Minimum Compatible Rope Diameter',
  'Minimum Compatible Rope Diameter Unit Of Measure',
  'CompatibleRopeDiameter',
  'Maximum Compatible Rope Diameter Unit Of Measure',
  'Effective Edge Length',
  'Effective Edge Length Unit Of Measure',
  'Maximum Height Recommendation',
  'Maximum Height Recommendation Unit Of Measure',
  'Breaking Strength',
  'Breaking Strength Unit Of Measure',
  'Tensile Strength Max',
  'Tensile Strength Unit Of Measure',
  'Cross Section Shape',
  'Objective Lens Diameter',
  'Objective Lens Diameter Unit Of Measure',
  'Shaft Length',
  'Shaft Length Unit Of Measure',
  'Display Maximum Weight Recommendation',
  'Display Maximum Weight Recommendation Unit Of Measure',
  'Load Capacity',
  'Load Capacity Unit Of Measure',
  'Display Size',
  'Display Size Unit Of Measure',
  'Minimum Weight Recommendation',
  'Minimum Weight Recommendation Unit Of Measure',
  'Coverage Area',
  'Item Area Unit Of Measure',
  'Display Height',
  'Thickness Derived',
  'Base Width',
  'Maximum Height',
  'Base Width Unit Of Measure',
  'Maximum Height Unit',
  'Weight Recommendation Unit Of Measure',
  'Item Length Longer Edge',
  'Item Length Unit',
  'Maximum Expandable Size',
  'Maximum Size Unit Of Measure',
  'Line Size',
  'Line Size Unit Of Measure',
  'paper-size',
  'Paper Size Unit of Measure',
  'Head Diameter Tolerance Unit',
  'Head Height Tolerance Unit',
  'Head Height Tolerance',
  'Head Diameter Tolerance',
  'Housing Height',
  'Housing Height Unit Of Measure',
  'Outside Diameter',
  'Tubing Outside Diameter Unit Of Measure',
  'Item Length Longer Edge',
  'Item Length Unit',
  'Item Width Shorter Edge',
  'Item Width Unit',
  'Arm Length',
  'Arm Length Unit',
  'Item Width Side to Side',
  'Item Height Unit',
  'Height Top to Bottom',
  'Item Width Unit',
  'Cord Length',
  'Strand Diameter Unit Of Measure',
  'Product Grade',
  'Maximum Focal Length',
  'Maximum Focal Length Unit',
  'Tweeter Speaker Diameter',
  'Tweeter Driver Diameter Unit Of Measure',
  'Woofer Speaker Diameter',
  'Woofer Driver Diameter Unit Of Measure',
  'Subwoofer Speaker Diameter',
  'Subwoofer Diameter Unit Of Measure',
  'Package Length',
  'Package Weight Unit Of Measure',
  'Package Height',
  'Package Length Unit Of Measure',
  'Package Height Unit Of Measure',
  'Package Width',
  'Package Width Unit Of Measure',
  'Package Weight',
  'Is Fragile?',
  'Package Dimensions Unit Of Measure',
  'Compliance Regulation Type',
  'Compliance Regulation Type',
  'Compliance Regulation Type',
  'Compliance Regulation Type',
  'Compliance Regulation Type',
  'Regulatory Identification',
  'Regulatory Identification',
  'Regulatory Identification',
  'Regulatory Identification',
  'Regulatory Identification',
  'Cpsia Warning',
  'Cpsia Warning',
  'Cpsia Warning',
  'Cpsia Warning',
  'Item Weight Unit',
  'Item Weight',
  'Is this product a battery or does it utilize batteries?',
  'Batteries are Included',
  'Number of batteries',
  'Number of batteries',
  'Number of batteries',
  'Battery type/size',
  'Battery type/size',
  'Battery type/size',
  'Battery composition',
  'Battery weight (grams)',
  'Battery Weight Unit',
  'Number of Lithium Metal Cells',
  'Number of Lithium-ion Cells',
  'Lithium Battery Packaging',
  'Watt hours per battery',
  'Lithium Battery Energy Content Unit',
  'Lithium content (grams)',
  'Lithium Battery Weight Unit',
  'Dangerous Goods Regulations',
  'Dangerous Goods Regulations',
  'Dangerous Goods Regulations',
  'Dangerous Goods Regulations',
  'Dangerous Goods Regulations',
  'Hazmat',
  'Safety Data Sheet (SDS or MSDS) URL',
  'Volume',
  'item_volume_unit_of_measure',
  'Country of Origin',
  'legal_compliance_certification_expiration_date',
  'Regulatory Organization Name',
  'Compliance Certification Status',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Compliance Media Content Type',
  'Flash point (°C)?',
  'Manufacturer Warranty Description',
  'Certification Date of Issue',
  'Compliance Certification Value',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Compliance Media Source Location',
  'Legal Compliance Certification',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'Compliance Media Language',
  'GHS Class',
  'GHS Class',
  'GHS Class',
  'California Proposition 65 Warning Type',
  'California Proposition 65 Chemical Name(s)',
  'Additional Chemical Name1',
  'Additional Chemical Name2',
  'Additional Chemical Name3',
  'Additional Chemical Name4',
  'Pesticide Marking',
  'Pesticide Marking',
  'Pesticide Marking',
  'Pesticide Registration Status',
  'Pesticide Registration Status',
  'Pesticide Registration Status',
  'Pesticide Certification Number',
  'Pesticide Certification Number',
  'Pesticide Certification Number',
  'Radio Frequency Emission & Authorization Status',
  'SDoC Contact Email Address',
  'SDOC Contact US Phone Number',
  'SDoC Contact Name',
  'FCC ID',
  'SDoC Contact US Mailing Address',
  'Specific Uses',
  'Specific Uses',
  'Specific Uses',
  'Specific Uses',
  'Specific Uses',
  'Fabric Type',
  'Fabric Type',
  'Fabric Type',
  'Fabric Type',
  'Fabric Type',
  'Tuner Type',
  'CPSIA Warning Description',
  'Legal Disclaimer',
  'Country/Region of Origin',
  'Region of Origin',
  'Contains Liquid Contents?',
  'Safety Warning',
  'Mfg Warranty Type (i.e. Parts, Labor)',
  'Import Designation',
  'Ingredients',
  'External Testing Certification',
  'Lighting Facts Label',
  'Energy Guide Label',
  'USDA Hardiness Zone',
  'USDA Hardiness Zone',
  'Is the Item Heat Sensitive?',
  'Liquid Contents Description',
  'Warranty Type',
  'Item Condition',
  'Offer Condition Note',
  'Product Tax Code',
  'Release Date',
  'List Price',
  'Offering Can Be Gift Messaged',
  'Is Gift Wrap Available',
  'Number of Items',
  'Max Order Quantity',
  'Shipping-Template',
  'Package Quantity',
  'Seller Warranty Description',
  'Max Aggregate Ship Quantity',
  'Is Discontinued by Manufacturer',
  'Scheduled Delivery SKU List',
  'Signed By',
  'Is Product Expirable',
  'Fulfillment Center Shelf Life',
  'Product Expiration Type',
  'Fulfillment Channel Code (US)',
  'Quantity (US)',
  'Handling Time (US)',
  'Restock Date (US)',
  'Inventory Always Available (US)',
  'Your Price USD (US)',
  'Pricing Rule (US)',
  'Minimum Seller Alllowed Price (US)',
  'Maximum Seller Allowed Price (US)',
  'Sale Price USD (US)',
  'Sale Start Date (US)',
  'Sale End Date (US)',
  'Offering Release Date (US)',
  'Stop Selling Date (US)',
  'Business Price',
  'Quantity Price Type',
  'Quantity Lower Bound 1',
  'Quantity Price 1',
  'Quantity Lower Bound 2',
  'Quantity Price 2',
  'Quantity Lower Bound 3',
  'Quantity Price 3',
  'Quantity Lower Bound 4',
  'Quantity Price 4',
  'Quantity Lower Bound 5',
  'Quantity Price 5',
  'Progressive Discount Type',
  'Progressive Discount Lower Bound 1',
  'Progressive Discount Value 1',
  'Progressive Discount Lower Bound 2',
  'Progressive Discount Value 2',
  'Progressive Discount Lower Bound 3',
  'Progressive Discount Value 3',
  'National Stock Number',
  'United Nations Standard Products and Services Code',
  'Pricing Action',
  'Age Range Description'
];
